inherit_from: .rubocop_todo.yml

require:
  - rubocop/cop/internal_affairs
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

InternalAffairs/NodeMatcherDirective:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/NumericPredicate:
  Enabled: false

Style/RedundantPercentQ:
  Exclude:
    - '*.gemspec'

Style/ModuleFunction:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  Exclude:
    - '*.gemspec'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Naming/FileName:
  Exclude:
    - 'lib/rubocop-rake.rb'

RSpec:
  Language:
    Expectations:
      - expect_correction
      - expect_no_offenses
      - expect_offense

RSpec/ExampleLength:
  Enabled: false

# This disabling is a workaround for https://github.com/rubocop-hq/rubocop-rspec/issues/1068.
# The cop has been disabled because FactoryBot is not used in this repository.
RSpec/FactoryBot/CreateList:
  Enabled: false
